spring:
  mail:
    host: smtp.gmail.com
    username: mwangedennis05@gmail.com
    password: gylb mwyv qcal igiv
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true